use_frameworks!

platform :ios, '8.0'

target 'CNLiveNewDome_Example' do
  pod 'CNLiveNewDome', :path => '../'

  target 'CNLiveNewDome_Tests' do
    inherit! :search_paths

    pod 'MJExtension'

  end
end
