use_frameworks!

platform :ios, '9.0'

target 'CNLiveNewDome_Example' do
  pod 'CNLiveNewDome', :path => '../'
  pod 'MJExtension'

  target 'CNLiveNewDome_Tests' do
    inherit! :search_paths

    pod 'MJExtension'

  end
end
